# Deep Learning


In [7]:
import torch


In [8]:
torch.cuda.is_available()

False

In [9]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [10]:
df = pd.read_csv("./Iris.csv ")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [11]:
df.shape

(150, 6)

In [21]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
le = LabelEncoder()
X = df.drop(['Species'], axis=1).values
y = le.fit_transform(df['Species'].values)


#chia dữ liệu tới test size = 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)



In [22]:
len(y_train)

120

In [23]:
labels, counts = y_train.unique(return_counts=True)
print(labels, counts)


tensor([0, 1, 2]) tensor([40, 41, 39])


In [ ]:
#Tính đạo hàm bằng PyTorch Autograd
#Cho y 2x^4 + x^3 +3x^2 +5x + 1


In [24]:
import torch

In [25]:
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [26]:
#Định nghia hàm số y
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [27]:
y.grad_fn

In [28]:
#Thực hiện lan truyền ngược và tính toán các gradient
y.backward()

In [29]:
#8x^3 + 3x^2 + 6x + 5 tại x = 2
x.grad

tensor(93.)

In [ ]:
#BT1
#Cho y = 5x^5 + 6x^3 - 3x + 1
#Cho biết độ dốc của đa thức trên ở điểm nào

In [ ]:
import torch

# Khởi tạo giá trị x
x = torch.tensor(1.0, requires_grad=True)

# Định nghĩa hàm số
y = 5*x**5 + 6*x**3 - 3*x + 1

# Tính đạo hàm
y.backward()

print(f"Độ dốc của hàm số tại x = 1.0 là: {x.grad.item()}")

Độ dốc của hàm số tại x = 1.0 là: 40.0


In [ ]:
#BT2 
# Tạo một tensor ban đầu có giá trị là 2
# Định nghĩa hàm số y = x^3 + 2x^2 + 5x + 1
#hãy tính dy/dx tại điểm x = 2 sử dụng PyTorch Autograd
#Dùng phương pháp gradient descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lập

In [ ]:
import torch

# Tạo tensor ban đầu có giá trị là 2
x = torch.tensor(2.0, requires_grad=True)
learning_rate = 0.1

print("--- Quá trình tối ưu hóa ---")

# Vòng lặp Gradient Descent (10 lần)
for i in range(10):
    # Định nghĩa hàm số
    y = x**3 + 2*x**2 + 5*x + 1
    
    # Tính dy/dx tại x hiện tại
    if x.grad is not None:
        x.grad.zero_()
        
    y.backward()
    
    # In kết quả đạo hàm tại x = 2 ở vòng lặp đầu tiên
    if i == 0:
        print(f"Đạo hàm dy/dx tại x=2 ban đầu là: {x.grad.item()}")

    # Cập nhật giá trị x: x = x - alpha * dy/dx
    with torch.no_grad():
        x -= learning_rate * x.grad
        
    print(f"Vòng lặp {i+1}: x = {x.item():.4f}, y = {y.item():.4f}")

print(f"\nGiá trị x cuối cùng sau 10 vòng lặp: {x.item():.4f}")

--- Quá trình tối ưu hóa ---
Đạo hàm dy/dx tại x=2 ban đầu là: 25.0
Vòng lặp 1: x = -0.5000, y = 27.0000
Vòng lặp 2: x = -0.8750, y = -1.1250
Vòng lặp 3: x = -1.2547, y = -2.5137
Vòng lặp 4: x = -1.7251, y = -4.1001
Vòng lặp 5: x = -2.4278, y = -6.8073
Vòng lặp 6: x = -3.7250, y = -13.6609
Vòng lặp 7: x = -6.8977, y = -41.5604
Vòng lặp 8: x = -18.9120, y = -266.5102
Vòng lặp 9: x = -119.1464, y = -6142.3750
Vòng lặp 10: x = -4330.7476, y = -1663589.5000

Giá trị x cuối cùng sau 10 vòng lặp: -4330.7476


In [31]:
import torch
import numpy as np

In [32]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))


[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [33]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [34]:
print(x.dtype)

torch.int32


In [35]:
print(x.type())

torch.IntTensor


In [36]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2


array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [37]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [38]:
#copy and sharing
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [39]:
arr[0] = 99
print(x)

tensor([99,  2,  3,  4,  5], dtype=torch.int32)


In [40]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [41]:
arr[0] = 0
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [ ]:
#BTVN 3:
# Tạo một tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1- 10) và y là điểm được tính theo công thức
# y = 3x + 5 + noise với noise là một giá trị ngẫu nhiên nhỏ
# Khởi tạp tham số w và b ngẫu nhiên với requires_grad=True
# Tính MSE
# Tính gradient 
# Cập nhật tham số w và b bằng gradient descent với learning rate alpha = 0.01
# Lập ại quá trình trên trong 100 vòng lập để xem sự hội tụ của mô hình 

In [ ]:
import torch

# Tạo dữ liệu giả lập
torch.manual_seed(42) # Để kết quả giống nhau mỗi lần chạy
x = torch.randint(1, 11, (100, 1), dtype=torch.float32)
noise = torch.randn(100, 1) * 0.5
y_true = 3 * x + 5 + noise

# Khởi tạo tham số w và b
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

learning_rate = 0.01

# Vòng lặp huấn luyện 100 
for epoch in range(100):
    # Dự báo 
    y_pred = x * w + b
    
    # Tính MSE
    loss = torch.mean((y_pred - y_true)**2)
    
    # Tính gradient 
    loss.backward()
    
    # Cập nhật tham số bằng Gradient
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        
        # Xóa gradient sau mỗi cập nhật
        w.grad.zero_()
        b.grad.zero_()
    
    if (epoch + 1) % 20 == 0:
        print(f"Epoch {epoch+1}: Loss = {loss.item():.4f}, w = {w.item():.4f}, b = {b.item():.4f}")

print(f"\nKết quả sau cùng: w ≈ {w.item():.2f}, b ≈ {b.item():.2f}")

Epoch 20: Loss = 4.8798, w = 3.6448, b = 0.4434
Epoch 40: Loss = 4.0778, w = 3.5893, b = 0.8384
Epoch 60: Loss = 3.4122, w = 3.5387, b = 1.1983
Epoch 80: Loss = 2.8599, w = 3.4927, b = 1.5262
Epoch 100: Loss = 2.4016, w = 3.4507, b = 1.8249

Kết quả sau cùng: w ≈ 3.45, b ≈ 1.82


In [ ]:

#BTVN 4: Giải thích 2 trường hợp ở trên

#Trường hợp 1: torch.from_numpy(arr) chia sẻ bộ nhớ với numpy array, nên khi thay đổi giá trị trong arr, giá trị trong x cũng thay đổi.
# Thay đổi giá trị trong mảng Numpy gốc, giá trị trong Tensor cũng thay đổi theo và ngược lại. Nó giúp tiết kiệm bộ nhớ vì không tạo bản sao.
#Trường hợp 2: torch.tensor(arr) tạo một bản sao độc lập của dữ liệu, nên khi thay đổi giá trị trong arr, giá trị trong x không bị ảnh hưởng.
# Dữ liệu được chép sang một vùng nhớ mới. Khithay đổi mảng Numpy gốc, Tensor sẽ không bị ảnh hưởng. 


In [ ]:
#BTVN 5
# Bạn giúp thầy tạo tensor với
#empyty
#zeros
#ones
#random
#reshape với view và view as

In [5]:
import torch

# 1. Tạo các loại Tensor
empty_t = torch.empty(2, 3)          # Tensor rỗng
zeros_t = torch.zeros(2, 3)          #  0
ones_t  = torch.ones(2, 3)           #  1
rand_t  = torch.rand(2, 3)           # Giá trị ngẫu nhiên từ [0, 1)

# 2. Thay đổi hình dạng 
original = torch.arange(12)          # Tạo tensor [0, 1, ..., 11]

# Chia sẻ bộ nhớ, yêu cầu tensor phải liên tục 
view_t = original.view(3, 4)

# Sử dụng reshape
reshape_t = original.reshape(2, 6)

# Thay đổi kích thước dựa trên một tensor khác có sẵn
target_shape = torch.empty(4, 3)
view_as_t = original.view_as(target_shape)

print(f"Original shape: {original.shape}")
print(f"View shape: {view_as_t.shape}")

Original shape: torch.Size([12])
View shape: torch.Size([4, 3])
