In [1]:
# Numpy là thư viện kiểu list
# Vì: numpy nhanh, có nhiều hàm tích hợp dễ sử dụng cho AI
# Để sử dụng numpy thì : pip install numpy
import numpy as np


In [2]:
# Thử tạo 1 list
python_list = [1, 2, 3]
#Chuyển đổi danh sách trên thành numpy list
numpy_list = np.array(python_list)
type(numpy_list)




numpy.ndarray

In [3]:
# list trong python có thể hổ trợ nhiều loại dữ liệu khác nhau trong cùng 1 list
my_list = [1, "Hello", 3.4, True]

In [4]:
my_list = [1,2,3,4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [5]:
#Chuyển đổi kiểu dữ liệu

np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [6]:
#accessing và indexing trong numpy
x = np.array([1,2,3,4,5,6,7,8]) # x = np.array(range(1,9))

In [7]:
# lấy số 4
x[3]

4

In [12]:
#lấy nhiều phần từ hơn 1 phần tử
#công thức [start:stop:step]
#lấy 1 2 3
x[0:3]

array([1, 2, 3])

In [ ]:
#lấy từ 3 - 8 theo 3 cách
#cách 1
x[2:8]
#cách 2
x[2:]


array([3, 5])

In [ ]:
#lấy số 3 và số 5
x[2:6:2]

In [16]:
#đặt danh sách các index muốn truy cập
x[[2,4]]

array([3, 5])

In [17]:
data = [[1,2], [3,4], [5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#lấy số 6
np_list[2,1]
#lấy [3,4],[5,6]
np_list[1:, :]
np_list[[1,2], :]
np_list[1:,0:2]


array([[3, 4],
       [5, 6]])

In [40]:
# lấy 1 3 5
np_list[:,0]



array([1, 3, 5])

In [ ]:
# lấy 1 và 5 theo 2 cách
np_list[[0,2],0]
np_list[[0,2]][:,0]
#giải thích: np_list[[0,2]][:,0] = lấy hàng 0 và 2 rồi lấy cột 0

array([1, 5])

In [ ]:
x = ([[1,2,3,4],
      [5,6,7,8],
      [9,10,11,12],
      [13,14,15,16]])

# lấy số 2 6 10 14
np.array(x)[:,1]
#giải thích: np.array(x)[:,1] = lấy tất cả các hàng (:) của cột 1

array([ 2,  6, 10, 14])

In [ ]:
#lấy số 7 và số 11
np.array(x)[1:3,2]
#giải thích: np.array(x)[1:3,2] = lấy hàng 1 đến hàng 2 của cột 2

array([ 7, 11])

In [ ]:
#lấy 4 7 10
np.array(x)[::3,1:3]
#giải thích: np.array(x)[::3,1:3] = lấy từ hàng đầu tiên đến hàng cuối cùng với bước nhảy là 3, lấy cột 1 đến cột 2

In [57]:
#lấy 16 15 14 13
np.array(x)[3, ::-1]    
#giải thích: np.array(x)[3, ::-1] = lấy hàng 3, từ cột cuối cùng đến cột đầu tiên với bước nhảy là -1 (nghĩa là lùi lại)
#cách 2
np.array(x)[3][::-1]

array([16, 15, 14, 13])

In [ ]:
#BTVN
# cho ma trận =[[99,99,99],
#              [99,99,99],
#              [99,99,99]],
#hãy tưởng tượng ô 99 trống
#giả sử 1 là x
# Giả sử 0 là o


#lấy đầu vào từ phía X cà phía O luân phiên
#nếu đầu vào từ phía X là (0,0)

#ma trận sẽ trở thành
#[[x,99,99],
#[99,99,99],
#[99,99,99]]

#Nếu đầu vào từ phía O là (0,0)
#thông báo họ nhập sai, vui lòng nhập lại
#nếu không thì điền vào ma trận

#Thử thách: nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi.

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
# Khởi tạo ma trận 3x3 với giá trị 99 
board = [
    [99, 99, 99],
    [99, 99, 99],
    [99, 99, 99]
]

# Hàm hiển thị bàn cờ cho dễ nhìn
def print_board():
    for row in board:
        # Chuyển đổi 99 thành '.', 1 thành 'X', 0 thành 'O'
        display_row = [('X' if cell == 1 else ('O' if cell == 0 else '.')) for cell in row]
        # tạo danh sách mới hiển thị trạng thái của mỗi ô trong hàng
        print(" | ".join(display_row))
    print("-" * 10)

# Hàm kiểm tra xem đã có người thắng chưa
def check_winner():
    # Kiểm tra hàng ngang và cột dọc
    for i in range(3):
        if board[i][0] == board[i][1] == board[i][2] != 99: return True
        if board[0][i] == board[1][i] == board[2][i] != 99: return True
    
    # Kiểm tra 2 đường chéo
    if board[0][0] == board[1][1] == board[2][2] != 99: return True
    if board[0][2] == board[1][1] == board[2][0] != 99: return True
    
    return False

# Biến điều khiển lượt chơi (True là X, False là O)
is_x_turn = True
turns = 0

print("Chào mừng đến với game Tic-Tac-Toe!")
print_board()

while turns < 9:
    player = "X" if is_x_turn else "O"
    val = 1 if is_x_turn else 0
    
    print(f"Lượt của người chơi {player}")
    
    try:
        # Nhập tọa độ hàng và cột
        row = int(input("Nhập hàng (0, 1, 2): "))
        col = int(input("Nhập cột (0, 1, 2): "))
        
        # Kiểm tra tọa độ hợp lệ
        if row not in [0, 1, 2] or col not in [0, 1, 2]:
            print("Tọa độ không hợp lệ! Vui lòng nhập từ 0 đến 2.")
            continue
            
        # Kiểm tra ô đã có người đi chưa
        if board[row][col] != 99:
            print("Ô này đã có người đi rồi! Vui lòng nhập lại.")
            continue
            
        # Điền vào ma trận
        board[row][col] = val
        print_board()
        turns += 1
        
        # Kiểm tra điều kiện thắng
        if check_winner():
            print(f"Chúc mừng! Người chơi {player} đã thắng!")
            break
            
        # Đổi lượt
        is_x_turn = not is_x_turn
        
    except ValueError:
        print("Vui lòng chỉ nhập số nguyên!")

if turns == 9 and not check_winner():
    print("Hòa rồi!")
    

Chào mừng đến với game Tic-Tac-Toe!
. | . | .
. | . | .
. | . | .
----------
Lượt của người chơi X
Vui lòng chỉ nhập số nguyên!
Lượt của người chơi X


In [ ]:
#BTVN 
# y = [[1,2,3],
#      [4,5,6],
#      [7,8,9]]
# lấy 4,5,6
#lấy 2,5
#lấy 3,4
#lấy 9,6,3



In [ ]:
# Khởi tạo ma trận y
y = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

# 1. Lấy hàng [4, 5, 6]
# Dòng này là phần tử thứ 2 trong y 
lay_456 = y[1]
print("Lấy 4,5,6:", lay_456)

# 2. Lấy 2, 5
# Số 2 ở hàng 0, cột 1 | Số 5 ở hàng 1, cột 1
lay_25 = [y[0][1], y[1][1]]
print("Lấy 2,5:", lay_25)

# 3. Lấy 3, 4
# Số 3 ở hàng 0, cột 2 | Số 4 ở hàng 1, cột 0
lay_34 = [y[0][2], y[1][0]]
print("Lấy 3,4:", lay_34)

# 4. Lấy 9, 6, 3
#(cột 2), đi ngược từ hàng 2 -> 1 -> 0
lay_963 = [y[2][2], y[1][2], y[0][2]]
print("Lấy 9,6,3:", lay_963)

Lấy 4,5,6: [4, 5, 6]
Lấy 2,5: [2, 5]
Lấy 3,4: [3, 4]
Lấy 9,6,3: [9, 6, 3]


In [ ]:
#BTVN 3:
# Cho x = [1,2,3,4,5,6,7,8,9,10]
# Xuất ra các giá trị chẵn sử dụng if
# xuất ra các giá trị chẵn sử dụng líst comprehension
# 

In [ ]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Xuất ra các giá trị chẵn sử dụng if 
print("Sử dụng if:")
for i in x:
    if i % 2 == 0:
        print(i, end=" ")

print("\n" + "-"*20)

# Xuất ra các giá trị chẵn 
chan_list = [i for i in x if i % 2 == 0]

print("Sử dụng List Comprehension:")
print(chan_list)

Sử dụng if:
2 4 6 8 10 
--------------------
Sử dụng List Comprehension:
[2, 4, 6, 8, 10]


In [58]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [60]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [62]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
idx = [True, False, True, False, True, False, True, False, True, False]
np_x[idx]

array([0, 2, 4, 6, 8])

In [65]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0


np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#BTVN 
# tạo một mảng numpy có kích thường 150x5.Giả sử mảng này chứa 150 mẫu dữ liệu của sinh viên bao gồm chiều cao, cân nặng,
# tuổi, lương và điểm trung bình
# tách mảng dựa trên 4 cột đầu tiên thành một biến có tên là X là 
# cột cuối cùng thành y

# tách X thành X_train và X_test trong đó x_train chứa 70% dữ liệu và tách t
# thành Y_train và Y_test trong đó Y_train chứa 70% dữ liệu

# Tạo 10 tập dữ liệu X_train không chồng chéo nhau

In [ ]:
import numpy as np

#Tạo mảng numpy kích thước 150x5 với các giá trị ngẫu nhiên
# [Chiều cao, Cân nặng, Tuổi, Lương, Điểm TB]
data = np.random.rand(150, 5)

# X (4 cột đầu) và y (cột cuối)
X = data[:, :4]  # Lấy tất cả các hàng, từ cột 0 đến cột 3
y = data[:, 4]   # Lấy tất cả các hàng, cột chỉ số 4

#Tách X, y thành tập Train (70%) và Test (30%)
# Tính số lượng hàng cho tập train: 150 * 0.7 = 105
train_size = int(0.7 * len(X))

X_train = X[:train_size]
X_test = X[train_size:]

y_train = y[:train_size]
y_test = y[train_size:]

# Tạo 10 tập dữ liệu X_train không chồng chéo
# Vì X_train có 105 hàng, chia cho 10 tập thì mỗi tập có khoảng 10 phần tử.
# Ta dùng np.array để chia mảng thành các phần bằng nhau.
x_train_subsets = np.array_split(X_train, 10)


print(f"Kích thước X_train: {X_train.shape}")
print(f"Kích thước X_test: {X_test.shape}")
print(f"Số lượng tập con của X_train: {len(x_train_subsets)}")
print(f"Kích thước tập con đầu tiên: {x_train_subsets[0].shape}")

Kích thước X_train: (105, 4)
Kích thước X_test: (45, 4)
Số lượng tập con của X_train: 10
Kích thước tập con đầu tiên: (11, 4)
